### ISSUE TITLE
Reset didn't return promise.

### ISSUE THREAD

**Issue by stalkerg** [TehShrike/svelte-state-renderer#15]
This line:
https://github.com/TehShrike/svelte-state-renderer/blob/master/index.js#L65

should have return: `return render(renderContext, cb)` because you expect it here:
https://github.com/TehShrike/abstract-state-router/blob/master/index.js#L107

and without it, you just stuck in the transaction. (not finished)

**Comment by TehShrike** [comment]
ASR wraps all of the renderer functions with [`then-denodeify`](https://github.com/TehShrike/then-denodeify#readme) here: https://github.com/TehShrike/abstract-state-router/blob/2f50cb8e2a58361c7570bc09e38e81330ab17721/index.js#L381-L384

That behavior is mentioned in the [renderer documentation here](https://github.com/TehShrike/abstract-state-router/blob/master/renderer.md#what-is-a-renderer-really):

> All of the functions are asynchronous, and take an error-first callback function as the final argument - but if you're more of a promises type, you can return a promise instead, no problem.

So for now, renderer functions may either use node-style callbacks, or return a promise.

In practice, this means that the easiest way for any other consumer to use a renderer is to wrap the functions with `then-denodeify` before calling them.

In a future breaking version, I'd be fine with dropping support for node-style callbacks and only using Promises going forward.  I'm not sure there's enough benefit to justify updating all the renderers and publishing a breaking change to ASR right now, though.
