### ISSUE TITLE
Reloading current route

### ISSUE THREAD

**Issue by felipedrumond** [TehShrike/svelte-state-renderer#17]
Is there any way to reload the current route? I know I can just not use event.preventDefault() but that reloads the app as a whole.

**Comment by TehShrike** [comment]
What's the use case?

This sounds like more of a general abstract-state-router best-practices question than a svelte-state-renderer question - feel free to bring up your use case in [the chat room](https://discord.gg/G8FrErC)

**Comment by felipedrumond** [comment]
Thanks @TehShrike will ask there.
