### ISSUE TITLE
Any plans to update this for Svelte 3?

### ISSUE THREAD

**Issue by ghost** [TehShrike/svelte-state-renderer#18]

**Comment by TehShrike** [comment]
Yeah!  I've got it started in a local branch, but haven't got it finished yet.  I started a new job recently and haven't been able to put a ton of time into open source side work.  This is on my short list, though.

**Comment by C02Equinox** [comment]
I'm just coming to use Svelte 3 now with no prior knowledge of either projects. Will your repo currently not work with Svelte 3?

**Comment by stalkerg** [comment]
It's should be small changes.

**Comment by TehShrike** [comment]
Closed by 2e741d407f076a5016796663c563d8419a6e4c06

**Comment by TehShrike** [comment]
`svelte-state-renderer@3` should be `svelte@3` compatible.
