### ISSUE TITLE
Self reference in component throws error

### ISSUE THREAD

**Issue by saibotsivad** [TehShrike/svelte-state-renderer#3]
If I create a component like this and compile it using `svelte-cli` or browserify with `sveltify` it executes correctly:

```html
<!-- Navbar.html -->
<ul>
{{#each menu as item}}
    <li>
        {{item.label}}
        {{#if item.children}}
        <:Self menu="{{item.children}}" />
        {{/if}}
    </li>
{{/each}}
</ul>
```

And then use it with something like:

```js
const Navbar = require('./Navbar.html')

new Navbar({
    target: document.querySelector('main'),
    data: {
        menu: [{
            label: 'first',
            children: [{
                label: 'second'
            }]
        }]
    }
})
```

But if I create a state with a template that references the `Navbar.html` component, I get an error thrown:

```
template.components.Navbar is not a constructor
```

Thrown [here](https://github.com/TehShrike/svelte-state-renderer/blob/master/index.js#L27) in the svelte-state-renderer.

I would like to be able to write a failing test for you, but CI tests aren't implemented.

**Comment by TehShrike** [comment]
Unable to reproduce: https://github.com/TehShrike/svelte-state-renderer-repro

The `data` property is not passed to templates.  It is pure metadata for the state itself, not default data for instantiated components - like the [docs](https://github.com/TehShrike/abstract-state-router#staterouteraddstatename-route-defaultchild-data-template-resolve-activate-querystringparameters-defaultparameters) say, it's only passed to the `resolve` and `activate` functions.
